# Generated by Django 5.2.5 on 2025-08-28 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(db_column='IdPersona', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('documento', models.CharField(db_column='Documento', max_length=20, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=254, unique=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'T001Persona',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(db_column='IdTarea', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=200)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('fecha_limite', models.DateField(db_column='FechaLimite')),
                ('persona', models.ForeignKey(db_column='PersonaId', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='api_app.persona')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'T002Tarea',
            },
        ),
    ]
